import type { ValuationMarket } from "./types";

/** Valuation universe — FX / metals / commodities / equity indices. */
export const VALUATION_MARKETS: readonly ValuationMarket[] = [
  {
    id: "DXY",
    label: "DXY",
    subtitle: "U.S. Dollar Index",
    assetClass: "forex",
    model: "usd_index",
    yahooSymbol: "DXY",
  },
  {
    id: "EUR",
    label: "EURUSD",
    subtitle: "Euro / US Dollar",
    assetClass: "forex",
    model: "fx",
    yahooSymbol: "EUR",
    baseCcy: "EUR",
    quoteCcy: "USD",
  },
  {
    id: "GBP",
    label: "GBPUSD",
    subtitle: "British Pound / US Dollar",
    assetClass: "forex",
    model: "fx",
    yahooSymbol: "GBP",
    baseCcy: "GBP",
    quoteCcy: "USD",
  },
  {
    id: "JPY",
    label: "USDJPY",
    subtitle: "US Dollar / Japanese Yen",
    assetClass: "forex",
    model: "fx",
    yahooSymbol: "USDJPY",
    baseCcy: "USD",
    quoteCcy: "JPY",
  },
  {
    id: "AUD",
    label: "AUDUSD",
    subtitle: "Australian Dollar / US Dollar",
    assetClass: "forex",
    model: "fx",
    yahooSymbol: "AUD",
    baseCcy: "AUD",
    quoteCcy: "USD",
  },
  {
    id: "CAD",
    label: "USDCAD",
    subtitle: "US Dollar / Canadian Dollar",
    assetClass: "forex",
    model: "fx",
    yahooSymbol: "USDCAD",
    baseCcy: "USD",
    quoteCcy: "CAD",
  },
  {
    id: "CHF",
    label: "USDCHF",
    subtitle: "US Dollar / Swiss Franc",
    assetClass: "forex",
    model: "fx",
    yahooSymbol: "USDCHF",
    baseCcy: "USD",
    quoteCcy: "CHF",
  },
  {
    id: "NZD",
    label: "NZDUSD",
    subtitle: "New Zealand Dollar / US Dollar",
    assetClass: "forex",
    model: "fx",
    yahooSymbol: "NZDUSD",
    baseCcy: "NZD",
    quoteCcy: "USD",
  },
  {
    id: "GOLD",
    label: "GOLD",
    subtitle: "Gold",
    assetClass: "metal",
    model: "metal",
    yahooSymbol: "GOLD",
  },
  {
    id: "SILVER",
    label: "SILVER",
    subtitle: "Silver",
    assetClass: "metal",
    model: "metal",
    yahooSymbol: "SILVER",
  },
  {
    id: "PLATINUM",
    label: "PLATINUM",
    subtitle: "Platinum",
    assetClass: "metal",
    model: "metal",
    yahooSymbol: "PLATINUM",
  },
  {
    id: "PALLADIUM",
    label: "PALLADIUM",
    subtitle: "Palladium",
    assetClass: "metal",
    model: "metal",
    yahooSymbol: "PALLADIUM",
  },
  {
    id: "COPPER",
    label: "COPPER",
    subtitle: "Copper",
    assetClass: "metal",
    model: "metal",
    yahooSymbol: "COPPER",
  },
  {
    id: "OIL",
    label: "OIL",
    subtitle: "WTI Crude",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "OIL",
  },
  {
    id: "NATGAS",
    label: "NATGAS",
    subtitle: "Henry Hub Natural Gas",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "NATGAS",
  },
  {
    id: "WHEAT",
    label: "WHEAT",
    subtitle: "Wheat SRW",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "WHEAT",
  },
  {
    id: "CORN",
    label: "CORN",
    subtitle: "Corn",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "CORN",
  },
  {
    id: "SOYBEANS",
    label: "SOYBEANS",
    subtitle: "Soybeans",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "SOYBEANS",
  },
  {
    id: "COFFEE",
    label: "COFFEE",
    subtitle: "Coffee C",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "COFFEE",
  },
  {
    id: "COCOA",
    label: "COCOA",
    subtitle: "Cocoa",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "COCOA",
  },
  {
    id: "SUGAR",
    label: "SUGAR",
    subtitle: "Sugar No. 11",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "SUGAR",
  },
  {
    id: "COTTON",
    label: "COTTON",
    subtitle: "Cotton No. 2",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "COTTON",
  },
  {
    id: "CATTLE",
    label: "CATTLE",
    subtitle: "Live Cattle",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "CATTLE",
  },
  {
    id: "HOGS",
    label: "HOGS",
    subtitle: "Lean Hogs",
    assetClass: "commodity",
    model: "commodity",
    yahooSymbol: "HOGS",
  },
  {
    id: "SPX",
    label: "S&P 500",
    subtitle: "S&P 500 cash",
    assetClass: "equity",
    model: "equity",
    yahooSymbol: "SPX",
  },
  {
    id: "NAS100",
    label: "NASDAQ 100",
    subtitle: "Nasdaq-100 futures proxy",
    assetClass: "equity",
    model: "equity",
    yahooSymbol: "NAS100",
  },
  {
    id: "DOW",
    label: "DOW",
    subtitle: "Dow Jones Industrial",
    assetClass: "equity",
    model: "equity",
    yahooSymbol: "DJI",
  },
  {
    id: "RTY",
    label: "RUSSELL 2000",
    subtitle: "Russell 2000 cash",
    assetClass: "equity",
    model: "equity",
    yahooSymbol: "RTY",
  },
] as const;

export const DEFAULT_VALUATION_MARKET_ID = "GOLD";

export function getValuationMarket(id: string): ValuationMarket | undefined {
  const key = id.trim().toUpperCase();
  return VALUATION_MARKETS.find(
    (m) => m.id === key || m.label.toUpperCase() === key || m.yahooSymbol.toUpperCase() === key,
  );
}

export function valuationMarketsByClass(assetClass: ValuationMarket["assetClass"] | "all"): ValuationMarket[] {
  if (assetClass === "all") return [...VALUATION_MARKETS];
  return VALUATION_MARKETS.filter((m) => m.assetClass === assetClass);
}
